---
- name: For build server
  hosts: build
  become: yes

  tasks:
  - name: Ensure Nginx
    apt:
      name: nginx
      state: present

  - name: Replace header
    lineinfile:
      path: /var/www/html/index.html
      regexp: "Welcome to nginx!"
      line: "<p><script> document.write(new Date().toLocaleDateString()); </script></p>"
