---
- name: dz ansible
  hosts: build
  become: yes

  tasks:
  - name: java
    apt:
      name: default-jdk
      state: present

  - name: git
    apt:
      name: git
      state: present

  - name: maven
    apt:
      name: maven
      state: present

  - name: Clone from github
    git:
      repo: https://github.com/miladhub/calculator-servlet-example
      dest: /tmp/calculator-servlet-example/
      clone: yes

  - name: build
    command: mvn --batch-mode --quiet install
    args:
     chdir: /tmp/calculator-servlet-example/

  - name: Fetch from build
    fetch:
      src: /tmp/calculator-servlet-example/target/mycalcwebapp.war
      dest: /tmp/
      flat: true
  
- name: dz ansible
  hosts: prod
  become: yes

  tasks:    
  - name: java
    apt:
      name: default-jdk
      state: present

  - name: tomcat
    apt:
      name: tomcat9
      state: present

  - name: Copy to prod
    copy:
      src: /tmp/mycalcwebapp.war
      dest: "{{ansible_env$CATALINA_HOME}}/webapps/"

