---
- name: For build server
  hosts: build
  become: yes

  tasks:
  - name: check java
    apt:
      name: default-jdk
      state: present

  - name: check git
    apt:
      name: git
      state: present

  - name: check maven
    apt:
      name: maven
      state: present

  - name: clone from github
    git:
      repo: https://github.com/miladhub/calculator-servlet-example
      dest: /tmp/calculator-servlet-example/
      clone: yes

  - name: build app
    command: mvn --batch-mode --quiet install
    args:
     chdir: /tmp/calculator-servlet-example/

  - name: get war from build to master
    fetch:
      src: /tmp/calculator-servlet-example/target/mycalcwebapp.war
      dest: /tmp/
      flat: true
  
- name: for prod server
  hosts: prod
  become: yes

  tasks:    
  - name: check java
    apt:
      name: default-jdk
      state: present

  - name: check tomcat
    apt:
      name: tomcat9
      state: present

  - name: copy war from master to prod
    copy:
      src: /tmp/mycalcwebapp.war
      dest: /var/lib/tomcat9/webapps/

